// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOw7MPKdX7ITV_GUPyiQ02reYw8m6Z6U',
    appId: '1:518972764867:web:f36a892aa48d223a232876',
    messagingSenderId: '518972764867',
    projectId: 'chat-app-dbd1c',
    authDomain: 'chat-app-dbd1c.firebaseapp.com',
    storageBucket: 'chat-app-dbd1c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdnymTzSblDuyV_cAMwKryozxajo0tFn8',
    appId: '1:518972764867:ios:8a419d6f8e95ad93232876',
    messagingSenderId: '518972764867',
    projectId: 'chat-app-dbd1c',
    storageBucket: 'chat-app-dbd1c.firebasestorage.app',
    iosBundleId: 'com.example.providerTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOw7MPKdX7ITV_GUPyiQ02reYw8m6Z6U',
    appId: '1:518972764867:web:c19b5a354a533ea7232876',
    messagingSenderId: '518972764867',
    projectId: 'chat-app-dbd1c',
    authDomain: 'chat-app-dbd1c.firebaseapp.com',
    storageBucket: 'chat-app-dbd1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdnymTzSblDuyV_cAMwKryozxajo0tFn8',
    appId: '1:518972764867:ios:8a419d6f8e95ad93232876',
    messagingSenderId: '518972764867',
    projectId: 'chat-app-dbd1c',
    storageBucket: 'chat-app-dbd1c.firebasestorage.app',
    iosBundleId: 'com.example.providerTutorial',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1eFfwV5FoAaPwkTihhB80Oo-m0-hkPQ',
    appId: '1:518972764867:android:2837168f8ea358bf232876',
    messagingSenderId: '518972764867',
    projectId: 'chat-app-dbd1c',
    storageBucket: 'chat-app-dbd1c.firebasestorage.app',
  );

}